name: Build Branch
on:
  workflow_dispatch:
  push:
    branches: [ master, Development, Rimworld-Version-1.4 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prebuild
      run: |
        rm -rf AssemblyPublicizer csc.zip csc
        git clone https://github.com/CombatExtended-Continued/AssemblyPublicizer
        mkdir -p Assemblies
        mkdir -p ${{ runner.temp }}/downloads
        wget https://github.com/CombatExtended-Continued/roslyn/releases/download/CSC-13/csc.zip
        unzip csc.zip
    - name: remove loader
      run: |
        rm Assemblies/CombatExtendedLoader.dll
        
    - name: build core
      run: |
        TEMP=${{ runner.temp }}/ python Make.py --csproj Source/CombatExtended/CombatExtended.csproj --output Assemblies/CombatExtended.dll --download-libs --all-libs --publicizer $PWD/AssemblyPublicizer --csc $PWD/csc
        
    - name: build compat
      run: |
        TEMP=${{ runner.temp }}/ python BuildCompat.py --csc $PWD/csc
        
    - name: package
      run: |
        mkdir CombatExtended
        cp -r Source/ Assemblies/ About/ Defs/ Languages/ Patches/ Royalty/ Ideology/ Biotech/ Anomaly/ Sounds/ Textures/ ModPatches/ LoadFolders.xml README.md SupportedThirdPartyMods.md CombatExtended
        zip -9 -r build.zip CombatExtended
    - name: Upload to DO
      run: |
        printf "%s" "$SSH_KEY" > id_ecdsa
        echo "$SSH_KEY_PUB" > id_ecdsa.pub
        chmod 600 id_ecdsa
        echo put build.zip CombatExtended-${{ github.run_id }}.zip | sftp -oStrictHostKeyChecking=no -P 2022 -i ./id_ecdsa combatextended@combatextended.lp-programming.com
        echo put build.zip CombatExtended-latest.zip | sftp -oStrictHostKeyChecking=no -P 2022 -i ./id_ecdsa combatextended@combatextended.lp-programming.com
      
      shell: bash
      env:
        SSH_KEY: ${{secrets.ID_ECDSA}}
        SSH_KEY_PUB: ${{secrets.ID_ECDSA_PUB}}

